import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ControlsProvider from "@/components/controls-provider";
import { PrimeReactProvider } from "primereact/api";
import Tailwind from 'primereact/passthrough/tailwind';
import { KnobPassThroughType } from "primereact/knob";
import { SVGProps } from "react";

const inter = Inter({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${inter.className} antialiased`}
            >
                <PrimeReactProvider value={{
                    unstyled: true, pt: {
                        ...Tailwind,
                        knob: {
                            ...Tailwind.knob,
                            label: "text-white fill-white" as KnobPassThroughType<SVGProps<SVGTextElement>>,
                            range: 'stroke-current transition duration-100 ease-in stroke-muted fill-none' as KnobPassThroughType<SVGProps<SVGTextElement>>,
                            value: 'animate-dash-frame stroke-primary fill-none' as KnobPassThroughType<SVGProps<SVGTextElement>>
                        }
                    }
                }}>
                    <ControlsProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            enableSystem
                            disableTransitionOnChange
                        >
                            {children}
                        </ThemeProvider>
                    </ControlsProvider>
                </PrimeReactProvider>
            </body>
        </html>
    );
}
